name : basic java code check out  and build 
on : 
  push : 
      branches : 
              - main 
  jobs :
      job1 :
        runs-on: ubuntu-latest
        steps:
            - name: Clone the current repository on the runner
              uses: actions/checkout@v4
            - name: Setup Java 17 and maven 
              uses: actions/setup-java@v4
              with:
                  java-version: '17'
                  distribution: 'temurin'
            - run: mvn --batch-mode --update-snapshots verify
            - run: mkdir staging && cp target/*.jar staging
            - uses: actions/upload-artifact@v4
              with:
              name: Package
              path: staging
            - uses: actions/download-artifact
